### ISSUE TITLE
Issue #6: User can collect pickups

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/driving-game#11]
## 💰 Motivation

The user would probably like to have something to do while driving around.

## 📐 Plan

Add randomly-generated coins for the user to pick up.

## ✅ Task List

- [x] Find a suitable image for the coin pickups and add an example to the html code.
- [x] Use this example image to style the coin image (position: absolute, top, left properties, fixed width)
- [x] Add a example coin counter to the page and style it
- [x] Use this fixed image to update the JavaScript code to handle the collision of the car with the coin
   - [x] Upon collision with the car, coin should disappear
   - [x] Counter should increment by one
- [x] Add a coin generating function to the JavaScript code, which returns a DOM node corresponding to a coin image. This can be appended to the DOM manually at this point. Use the existing element as an example, then remove that element from the HTML
- [x] Create a function to randomly spawn 10 coins somewhere near the player (because the window is small)
   - [ ] ~~Try to ensure no coins spawn touching one another - use similar logic to the previously implemenet collision check~~ I'd really rather not attempt this one anymore!!
- [x] Use this function as a callback function to a DOMContentLoaded event listener (ie, the game loads with 10 coins spawned)
- [x] Add a timer function that spawns a new coin at periodic intervals, as long as there are less than 10 coins present
- [x] Clean up!!
