### ISSUE TITLE
Issue #2: User can turn their car

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a js data model that contains the car's current direction
- [x] Create classes in CSS that correspond to the car's current direction
- [x] Add a keydown event listener to the page in the js file
- [x] In the event listener callback function, check for arrow keys being pressed
   - [x] If an arrow key was pressed, update the car's current direction in the data model, based on the key pressed
   - [x] Update the current class being applied to the car element to change its direction
- [x] Add CSS transitions to make the rotation visually appealing
