### ISSUE TITLE
Issue #3: User can start their car

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add the car's location to the js data model to hold the car's current coordinates
- [x] Update the CSS positioning of the car to be absolute
- [x] Update the event listener to check for a keydown event on the spacebar
- [x] If the spacebar was pressed:
   - [x] update the data model to indicate car is moving (moving: true)
- [x] Make the position change every 16 milliseconds for smooth movement (setInterval())
   - [x] Within the callback function, update the data model with the current position
   - [x] Use the style property of the car element's js object to change the top and left box offset styles, using the position from the data model
